### PR TITLE
Use getattr to get __mro__ for objects without __mro__ attribute (i.e. old style python classes)

### PR DESCRIPTION
**Pull request by RaiaN**
python tests.py output:
----------------------------------------------------------------------
Ran 5 tests in 0.006s

OK

### CODE REVIEW

**Comment by RaiaN** [comment]
.....
----------------------------------------------------------------------
Ran 5 tests in 0.006s

OK

**Comment by robertwb** [comment]
This isn't quite right, as old-style classes don't have "empty" MROs. However, I pushed https://github.com/cython/backports_abc/commit/94294718c6293d1031228943590dc12fe772fa9b

**Comment by RaiaN** [comment]
Oh, my bad. Misinterpreted some information. Thank you!

**Comment by RaiaN** [comment]
Any chances that will be in pypi too?

**Pull request closed without merging**
